# Site

title: Database to Document in RMarkdown
handouts:
 - worksheet.Rmd
 - data/species.csv
 - data/animals.csv
 - data/plots.csv
 - data/README.md
tag: v0.0
lesson: 4
instructor: Ian Carroll
authors:
 - Ian Carroll

# Slides

slide_sorter:
 - redirect

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v1.2/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
